# arguments for dataset
dataset: isic
nclass: 2
crop_size: 224
data_root: "D:/isic2018_deal/"

# arguments for training
epochs: 300
batch_size: 8 # per GPU x 1 GPU
lr: 0.008
conf_thresh: 0.95
